# Generated by Django 2.2.2 on 2019-06-20 23:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    def forwards(apps, schema_editor):
        model_plan = apps.get_model('autenticacao', 'plano')

        model_plan.objects.create(nome='bronze')
        model_plan.objects.create(nome='prata')
        model_plan.objects.create(nome='ouro')

    def backwards(apps, schema_editor):
        model_plan = apps.get_model('autenticacao', 'plano')

        model_plan.objects.get(nome='bronze').delete()
        model_plan.objects.get(nome='prata').delete()
        model_plan.objects.get(nome='ouro').delete()

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
